In [17]:
import numpy as np

In [19]:
a=np.array([])
b=np.array([1,2,3,4])
c=np.array([[12,3,4],[4,5,8]])

In [20]:
print(a,b,c)

[] [1 2 3 4] [[12  3  4]
 [ 4  5  8]]


In [21]:
a

array([], dtype=float64)

In [22]:
b

array([1, 2, 3, 4])

In [26]:
type(b)

numpy.ndarray

In [23]:
c

array([[12,  3,  4],
       [ 4,  5,  8]])

In [24]:
type(a)

numpy.ndarray

In [25]:
type(c)

numpy.ndarray

In [27]:
c.ndim

2

In [28]:
a.ndim

1

In [29]:
b.ndim

1

In [30]:
a.size

0

In [31]:
b.size

4

In [32]:
c.size

6

In [33]:
c.shape

(2, 3)

In [34]:
v=[[1,2,3,],[1,2,3],[1,2,3]]

In [50]:
len(v)

3

In [36]:
v=np.array([[1,2,3,],[1,2,3],[1,2,3]])

In [37]:
v.size

9

In [38]:
v.shape

(3, 3)

In [39]:
v

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [40]:
d=[[1,2,3,],[1,2,3],[1,2,3]]

In [48]:
x=len(d)

In [49]:
print(x)

5


In [47]:
len(v)

3

In [43]:
d="hello"

In [46]:
len(v)

3

In [45]:
len(d)

5

In [57]:
z=np.array([[1,2,3,4],[1,2,3],[1,2,3,4]])

C:\Users\HP\AppData\Local\Temp\ipykernel_11988\240445812.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  z=np.array([[1,2,3,4],[1,2,3],[1,2,3,4]])


In [52]:
z.shape

(3, 4)

In [53]:
z.shape

(3, 4)

In [54]:
z

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])